-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 17:35:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `idclient` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `primer_cognom` VARCHAR(45) NULL,
  `segon_cognom` VARCHAR(45) NULL,
  `direccio` VARCHAR(45) NULL,
  `codi_postal` INT NULL,
  `localitat` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `telefon` INT NULL,
  PRIMARY KEY (`idclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`botiga` (
  `idbotiga` INT NOT NULL,
  `direccio` VARCHAR(45) NULL,
  `codi_postal` INT NULL,
  `localitat` VARCHAR(45) NULL,
  `provinica` VARCHAR(45) NULL,
  PRIMARY KEY (`idbotiga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipus_empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipus_empleat` (
  `idtipus_empleat` INT NOT NULL,
  `cuiner` TINYINT(1) NULL,
  `repartidor` TINYINT(1) NULL,
  PRIMARY KEY (`idtipus_empleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `idempleat` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `primer_cognom` VARCHAR(45) NULL,
  `segon_cognom` VARCHAR(45) NULL,
  `NIF` VARCHAR(45) NULL,
  `telefon` INT NULL,
  `tipus_empleat_idtipus_empleat` INT NOT NULL,
  `botiga_idbotiga` INT NOT NULL,
  PRIMARY KEY (`idempleat`),
  INDEX `fk_empleat_tipus_empleat1_idx` (`tipus_empleat_idtipus_empleat` ASC) VISIBLE,
  INDEX `fk_empleat_botiga1_idx` (`botiga_idbotiga` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_tipus_empleat1`
    FOREIGN KEY (`tipus_empleat_idtipus_empleat`)
    REFERENCES `mydb`.`tipus_empleat` (`idtipus_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleat_botiga1`
    FOREIGN KEY (`botiga_idbotiga`)
    REFERENCES `mydb`.`botiga` (`idbotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lliurament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lliurament` (
  `data_hora` DATETIME NULL,
  `empleat_idempleat` INT NOT NULL,
  `idlliurament` VARCHAR(45) NOT NULL,
  INDEX `fk_domicili_empleat1_idx` (`empleat_idempleat` ASC) VISIBLE,
  PRIMARY KEY (`idlliurament`),
  CONSTRAINT `fk_domicili_empleat1`
    FOREIGN KEY (`empleat_idempleat`)
    REFERENCES `mydb`.`empleat` (`idempleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipus_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipus_comanda` (
  `idtipus_comanda` INT NOT NULL,
  `recollir` TINYINT NULL,
  `lliurament` TINYINT NULL,
  PRIMARY KEY (`idtipus_comanda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `idcomanda` INT NOT NULL,
  `data_hora` VARCHAR(45) NULL,
  `preu_total` FLOAT NULL,
  `client_idclient` INT NOT NULL,
  `botiga_idbotiga` INT NOT NULL,
  `lliurament_idlliurament` VARCHAR(45) NOT NULL,
  `tipus_comanda_idtipus_comanda` INT NOT NULL,
  PRIMARY KEY (`idcomanda`),
  INDEX `fk_comanda_client_idx` (`client_idclient` ASC) VISIBLE,
  INDEX `fk_comanda_botiga1_idx` (`botiga_idbotiga` ASC) VISIBLE,
  INDEX `fk_comanda_lliurament1_idx` (`lliurament_idlliurament` ASC) VISIBLE,
  INDEX `fk_comanda_tipus_comanda1_idx` (`tipus_comanda_idtipus_comanda` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_client`
    FOREIGN KEY (`client_idclient`)
    REFERENCES `mydb`.`client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_botiga1`
    FOREIGN KEY (`botiga_idbotiga`)
    REFERENCES `mydb`.`botiga` (`idbotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_lliurament1`
    FOREIGN KEY (`lliurament_idlliurament`)
    REFERENCES `mydb`.`lliurament` (`idlliurament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_tipus_comanda1`
    FOREIGN KEY (`tipus_comanda_idtipus_comanda`)
    REFERENCES `mydb`.`tipus_comanda` (`idtipus_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `idpizza` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idpizza`),
  INDEX `fk_pizza_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguesa` (
  `idhamburguesa` INT NOT NULL,
  PRIMARY KEY (`idhamburguesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`beguda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`beguda` (
  `idbeguda` INT NOT NULL,
  PRIMARY KEY (`idbeguda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producte` (
  `idproducte` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `descripcio` VARCHAR(45) NULL,
  `imatge` BLOB NULL,
  `preu` FLOAT NULL,
  `beguda_idbeguda` INT NOT NULL,
  `hamburguesa_idhamburguesa` INT NOT NULL,
  `pizza_idpizza` INT NOT NULL,
  PRIMARY KEY (`idproducte`),
  INDEX `fk_producte_beguda1_idx` (`beguda_idbeguda` ASC) VISIBLE,
  INDEX `fk_producte_hamburguesa1_idx` (`hamburguesa_idhamburguesa` ASC) VISIBLE,
  INDEX `fk_producte_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  CONSTRAINT `fk_producte_beguda1`
    FOREIGN KEY (`beguda_idbeguda`)
    REFERENCES `mydb`.`beguda` (`idbeguda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producte_hamburguesa1`
    FOREIGN KEY (`hamburguesa_idhamburguesa`)
    REFERENCES `mydb`.`hamburguesa` (`idhamburguesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producte_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `mydb`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detall_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detall_comanda` (
  `iddetall_comanda` INT NOT NULL,
  `producte_idproducte` INT NOT NULL,
  `comanda_idcomanda` INT NOT NULL,
  `quantitat` VARCHAR(45) NULL,
  PRIMARY KEY (`iddetall_comanda`),
  INDEX `fk_detall_comanda_producte1_idx` (`producte_idproducte` ASC) VISIBLE,
  INDEX `fk_detall_comanda_comanda1_idx` (`comanda_idcomanda` ASC) VISIBLE,
  CONSTRAINT `fk_detall_comanda_producte1`
    FOREIGN KEY (`producte_idproducte`)
    REFERENCES `mydb`.`producte` (`idproducte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detall_comanda_comanda1`
    FOREIGN KEY (`comanda_idcomanda`)
    REFERENCES `mydb`.`comanda` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `universidad` ;

-- -----------------------------------------------------
-- Table `universidad`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`departamento` (
  `id` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `universidad`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`persona` (
  `id` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nif` VARCHAR(9) NULL DEFAULT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido1` VARCHAR(50) NOT NULL,
  `apellido2` VARCHAR(50) NULL DEFAULT NULL,
  `ciudad` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(9) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `sexo` ENUM('H', 'M') NOT NULL,
  `tipo` ENUM('profesor', 'alumno') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`nif` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `universidad`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`profesor` (
  `id_profesor` INT UNSIGNED NULL DEFAULT NULL,
  `id_departamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_profesor`),
  INDEX (`id_departamento` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_profesor`)
    REFERENCES `universidad`.`persona` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id_departamento`)
    REFERENCES `universidad`.`departamento` (`id`));


-- -----------------------------------------------------
-- Table `universidad`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`grado` (
  `id` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `universidad`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`asignatura` (
  `id` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `creditos` FLOAT UNSIGNED NOT NULL,
  `tipo` ENUM('básica', 'obligatoria', 'optativa') NOT NULL,
  `curso` TINYINT UNSIGNED NOT NULL,
  `cuatrimestre` TINYINT UNSIGNED NOT NULL,
  `id_profesor` INT UNSIGNED NULL DEFAULT NULL,
  `id_grado` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_profesor` ASC) VISIBLE,
  INDEX (`id_grado` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_profesor`)
    REFERENCES `universidad`.`profesor` (`id_profesor`),
  CONSTRAINT ``
    FOREIGN KEY (`id_grado`)
    REFERENCES `universidad`.`grado` (`id`));


-- -----------------------------------------------------
-- Table `universidad`.`curso_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`curso_escolar` (
  `id` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `anyo_inicio` YEAR NOT NULL,
  `anyo_fin` YEAR NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `universidad`.`alumno_se_matricula_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universidad`.`alumno_se_matricula_asignatura` (
  `id_alumno` INT UNSIGNED NOT NULL,
  `id_asignatura` INT UNSIGNED NOT NULL,
  `id_curso_escolar` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_alumno`, `id_asignatura`, `id_curso_escolar`),
  INDEX (`id_asignatura` ASC) VISIBLE,
  INDEX (`id_curso_escolar` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_alumno`)
    REFERENCES `universidad`.`persona` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `universidad`.`asignatura` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id_curso_escolar`)
    REFERENCES `universidad`.`curso_escolar` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
