-- MySQL Script generated by MySQL Workbench
-- Wed Jul 13 19:31:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul Ampolla` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` ;
USE `Cul Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul Ampolla`.`Direccio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul Ampolla`.`Direccio` (
  `Carrer` INT NOT NULL,
  `Numero` INT NOT NULL,
  `Pis` INT NOT NULL,
  `Porta` VARCHAR(45) NOT NULL,
  `Ciutat` VARCHAR(45) NOT NULL,
  `Codi_postal` INT NOT NULL,
  `Pais` VARCHAR(45) NOT NULL,
  `id_direccio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_direccio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul Ampolla`.`Proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul Ampolla`.`Proveidors` (
  `idProveidors` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Telefon` INT NOT NULL,
  `Fax` INT NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Direccio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveidors`),
  INDEX `fk_Proveidors_Adreça1_idx` (`Direccio` ASC) VISIBLE,
  CONSTRAINT `fk_Proveidors_Adreça1`
    FOREIGN KEY (`Direccio`)
    REFERENCES `Cul Ampolla`.`Direccio` (`id_direccio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul Ampolla`.`Montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul Ampolla`.`Montura` (
  `Pasta` TINYINT NULL,
  `Metàl.lica` TINYINT NULL,
  `idMontura` VARCHAR(45) NOT NULL,
  `Flotant` TINYINT NULL,
  PRIMARY KEY (`idMontura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul Ampolla`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul Ampolla`.`Ulleres` (
  `id_ulleres` INT NOT NULL,
  `Graduacio` VARCHAR(45) NOT NULL,
  `Color_montura` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Color_vidre1` VARCHAR(45) NOT NULL,
  `Color_vidre2` VARCHAR(45) NOT NULL,
  `Preu` FLOAT NOT NULL,
  `Montura` VARCHAR(45) NOT NULL,
  `Proveidors_idProveidors` INT NOT NULL,
  PRIMARY KEY (`id_ulleres`),
  INDEX `fk_Ulleres_Montura1_idx` (`Montura` ASC) VISIBLE,
  INDEX `fk_Ulleres_Proveidors1_idx` (`Proveidors_idProveidors` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Montura1`
    FOREIGN KEY (`Montura`)
    REFERENCES `Cul Ampolla`.`Montura` (`idMontura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Proveidors1`
    FOREIGN KEY (`Proveidors_idProveidors`)
    REFERENCES `Cul Ampolla`.`Proveidors` (`idProveidors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul Ampolla`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul Ampolla`.`Clients` (
  `idClients/es` INT NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Telefon` INT NOT NULL,
  `Correu_electronic` VARCHAR(45) NOT NULL,
  `Data_registre` DATETIME NOT NULL,
  `Venedor` VARCHAR(45) NOT NULL,
  `Recomenat_per` INT NOT NULL,
  `Direccio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClients/es`),
  INDEX `fk_Clients_Clients1_idx` (`Recomenat_per` ASC) VISIBLE,
  INDEX `fk_Clients_Adreça1_idx` (`Direccio` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Clients1`
    FOREIGN KEY (`Recomenat_per`)
    REFERENCES `Cul Ampolla`.`Clients` (`idClients/es`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_Adreça1`
    FOREIGN KEY (`Direccio`)
    REFERENCES `Cul Ampolla`.`Direccio` (`id_direccio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
